### ISSUE TITLE
Question: How to import a specific type?

### ISSUE THREAD

**Issue by Than-DE** [OlegGulevskyy/zendesk-types#1]
Hi,

thanks for creating these types - using them in conjunction with the ZafClient in the boilerplate repo, for example

```ts
zafClient.get("ticket.conversation")
```

works well and you get some useful type annotations. However, now I want to import the `Ticket` type into my codebase for type safety. How does that actually work? Ideally, I can do something like

```ts
import { Ticket } from 'zendesk-types'

interface Payload {
    ticket: Ticket
}
```

Thanks! Intending to contribute some types myself some time

**Comment by OlegGulevskyy** [comment]
Hey, types package is really far away from good but it helped me having some ticket types safety a bit back in the day, but I am not proud of the way it works. There is a way to do this, but it won't look pretty :)
You can do something like this
```tsx
import { TicketSidebar} from "zendesk-types/lib/apps/support/locations/ticket_sidebar"

const ticket: TicketSidebar["ticket"] = {
  id: 123
}

```
